CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	USER_ID INTEGER NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING(255) NOT NULL,
	LOGIN CHARACTER VARYING(255) NOT NULL,
	NAME CHARACTER VARYING(255),
	BIRTHDAY DATE NOT NULL,
	CONSTRAINT EMAIL_UNIQUE UNIQUE (EMAIL),
	CONSTRAINT LOGIN_UNIQUE UNIQUE (LOGIN),
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS (EMAIL);
CREATE UNIQUE INDEX IF NOT EXISTS LOGIN_UNIQUE_INDEX_4 ON PUBLIC.USERS (LOGIN);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_4 ON PUBLIC.USERS (USER_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.RATING (
	RATING_ID SMALLINT AUTO_INCREMENT,
	NAME CHARACTER LARGE OBJECT(10) NOT NULL,
	CONSTRAINT RATING_PK PRIMARY KEY (RATING_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	FILM_ID INTEGER AUTO_INCREMENT,
	NAME CHARACTER VARYING(255) NOT NULL,
	DESCRIPTION CHARACTER VARYING(255),
	RELEASE_DATE DATE NOT NULL,
	DURATION SMALLINT NOT NULL,
	RATING_ID SMALLINT NOT NULL,
	POPULARITY INTEGER,
	CONSTRAINT FILMS_PK PRIMARY KEY (FILM_ID),
	CONSTRAINT FILMS_RATING_FK_1 FOREIGN KEY (RATING_ID) REFERENCES PUBLIC.RATING(RATING_ID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRE (
	GENRE_ID SMALLINT AUTO_INCREMENT,
	NAME CHARACTER VARYING(255) NOT NULL,
	CONSTRAINT GENRE_PK PRIMARY KEY (GENRE_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRE (
	FILM_ID INTEGER NOT NULL,
	GENRE_ID SMALLINT NOT NULL,
	CONSTRAINT FILM_GENRE_GENRE_FK FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRE(GENRE_ID),
	CONSTRAINT FILM_GENRE_FILMS_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.LIKES (
	USER_ID INTEGER NOT NULL,
	FILM_ID INTEGER NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	IS_LIKE BOOLEAN NOT NULL,
	CONSTRAINT LIKES_USERS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID),
	CONSTRAINT LIKES_FILMS_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FOLLOWS (
	FOLLOWING_USER_ID INTEGER,
	FOLLOWED_USER_ID INTEGER,
	CREATED_AT TIMESTAMP NOT NULL,
	IS_CONFIRMED BOOLEAN NOT NULL,
	CONSTRAINT FOLLOWS_USERS_FK FOREIGN KEY (FOLLOWING_USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOLLOWS_USERS_FK_1 FOREIGN KEY (FOLLOWED_USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
